### ISSUE TITLE
Define some protocols for readable/writable etc

### ISSUE THREAD

**Issue by danthorpe** [danthorpe/YapDatabaseExtensions#39]

**Comment by danthorpe** [comment]
Okay, I thought it might be possible to decompose the read API into a `Readable` protocol, which could then be implemented in extensions to support general conformance for `YapDatabaseReadTransaction` etc.

However, this isn't actually possible. Because such a protocol would need to be generic, and, while we could write an implementation in an extension on the protocol, with generic where constraints for the result type (e.g. `Persistable` etc), then it would not be possible to have non-generic types conform to it. E.g. `YapDatabaseReadTransaction` couldn't conform to `Readable`.

So, then I thought, well, what if we can wrap, or subclass, a `YapDatabaseReadTransaction` in a generic type - well, that might work, but we wouldn't be able to actually define what the generic parameter is.

So, basically it's a no-go.

**Comment by DarthMike** [comment]
@danthorpe Would phantom types help with this one? Check the excellent [post](https://www.objc.io/blog/2014/12/29/functional-snippet-13-phantom-types/) at objc.io.

**Comment by danthorpe** [comment]
Hmm, maybe. I'll have another think about this. It's a good article, although it's focused on using the generic parameter for additional type safety, whereas here, we genuinely have a generic return type, which requires specific (self-reflective) constraints.

The issue with the generic parameter, is that this is the type of the consumers object/value. For example, you want to read a `Barcode` value type out of YapDatabase. This is how that currently works now:

``` swift
extension YapDatabaseReadTransaction {
    /**
    Reads the Value sored by key in this transaction.
    :param: key A String
    :returns: An optional Value
    */
    public func read<
        Value
        where
        Value: Saveable,
        Value: Persistable,
        Value.ArchiverType: NSCoding,
        Value.ArchiverType.ValueType == Value>(key: String) -> Value? {
            return Value.ArchiverType.unarchive(objectForKey(key, inCollection: Value.collection))
    }
}
```

So, lets say we want to write this in a protocol + extensions.

``` swift
protocol _Readable {
    func objectForKey(key: String, inCollection: String) -> AnyObject?
}

protocol Readable: _Readable {
    typealias ResultType
    func read(key: String) -> ResultType?
}

extension Readable where ResultType: Saveable, ResultType: Persistable, ResultType: NSCoding, ResultType.ArchiverType.ValueType == ResultType {
    func read(key: String) -> ResultType? {
        return ResultType.ArchiverType.unarchive(objectForKey(key, inCollection: ResultType.collection))
    }
}
```

So far this is exactly the same pretty much, although the benefit of the extension method, is that it's a lot easier to write and maintain, as the generic where constraint only needs to be written a few times - it's surprisingly difficult to get this consistent across all of the APIs, (Readable actually has about 10 APIs).

Now, the problem is, how can I actually make it so that a `YapDatabaseReadTransaction` or `YapDatabaseConnection` conforms, or vends a type conforming to `Readable`?

``` swift
extension YapDatabaseReadTransaction: Readable { } // Will not compile - non-generic type
```

Could go with a generic facade:

``` swift
struct ReadTransaction<ResultType> {
    let readTransaction: YapDatabaseReadTransaction
}
```

I'd then need to write a bunch of functions, with the correct generic where constraints, to create these wrapper types. Also, now they'd not be able to take advantage of any default implementation. So this doesn't gain us anything.

My other idea is to flip the API around...

``` swift
protocol SourceType {
    func objectForKey(key: String, inCollection: String) -> AnyObject?
}

protocol Readable {
    static func read(key: String, fromSource: SourceType) -> Self?
}
```

Going back to our `Barcode` example, we'd use it like...

``` swift
if let barcode = Barcode.read(key, fromSource: transaction) {
    print("Barcode: \(barcode))
}
```

And now we can write default implementations of `Readable` for particular types.

``` swift
extension Readable where Self: Saveable, Self: Persistable, Self.ArchiverType: NSCoding, Self.ArchiverType.ValueType == Self {
    static func read(key: String, fromSource: Source) -> Self? {
        return ArchiverType.unarchive(objectForKey(key, inCollection: collection))
    }
}
```

But, this is a pretty fundamental API change, so I'd only do it as an additional, and wouldn't replace the `.read()` or `.write()` APIs on transaction/connection.

**Comment by DarthMike** [comment]
@danthorpe I understand now, there is friction between non-generic types (YapDB) and generic ones.

I think there is the  tradeoff to keep this library as a set of minimal extensions on top of YapDB, and using all advanced features of the language.

**Comment by danthorpe** [comment]
Yeah, which is why I've left it as it is for now.

Very happy with the Swift 2.0 improvements for the archiving though. See notes: https://github.com/danthorpe/YapDatabaseExtensions/releases/tag/2.0.0 is so much nicer.
