### ISSUE TITLE
Is using newConnection() for all APIs performant in all situations?

### ISSUE THREAD

**Issue by DarthMike** [danthorpe/YapDatabaseExtensions#4]
Hi! Great work abstracting YapDB!

I'm wondering if using newConnection() for all exposed API calls is performant, as YapDatabase recommends to keep connections around for caching reasons.

I generally cache the connections in properties from where I'm accessing YapDB; Usually one for readonly operations which will have sync readonly calls, another one for readwrite operations which will have asynchronous calls.

Have you tried this in a big application and experienced any issues?

**Comment by DarthMike** [comment]
No worries, didn't see that there are extensions already for connection, so this is for ease of use. Nice :smile:

**Comment by danthorpe** [comment]
Hi @DarthMike - yeah, the `YapDatabase` API is mostly just for convenience (and it makes unit tests simpler). In general I would expect usage to be primarily on the `YapDatabaseReadTransaction` extension.

Have created an issue: #6.
