### ISSUE TITLE
Example code does not compile

### ISSUE THREAD

**Issue by toddwbates** [danthorpe/YapDatabaseExtensions#46]
ViewController is missing implementation?
Unit test files missing.

looking forward to trying this.

**Comment by danthorpe** [comment]
Hi @toddwbates are you trying the example on `development`? Not surprised that it doesn't compile - rewrote the whole API yesterday. Take a look at the unit tests to see how the API works though: https://github.com/danthorpe/YapDatabaseExtensions/blob/development/YapDatabaseExtensionsTests/ValueWithValueMetadataTests.swift#L130

**Comment by aranasaurus** [comment]
#42 also has a very useful description of said new API ;)

**Comment by danthorpe** [comment]
Might actually drop the example projects entirely, because they are not really needed - there isn't actually a UI, it's all in the tests. But the tests are in the framework, so kinda redundant. I'll sort it out when I take care of #43.

**Comment by danthorpe** [comment]
The example project has been removed - it wasn't much use, just some unit tests. Instead I'll add more documentation to the README, possibly the Wiki and the code itself. Will close this issue now.
