### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by JimRoepcke** [danthorpe/YapDatabaseExtensions#91]
Hi Dan, 

You [mentioned](https://github.com/danthorpe/YapDatabaseExtensions/pull/90#issuecomment-252449221) a Swift 3 port was in progress a while ago. My team's Swift 3 port is currently blocked by YapDatabaseExtensions, so if there's any way I can help with the this port, please let me know.

**Comment by danthorpe** [comment]
Hey @JimRoepcke - yep sorry, been distracted with other projects. Will finish of Swift 3 very soon though - hopefully Sunday.

**Comment by JimRoepcke** [comment]
It was exciting to see the Swift 2.3 branch cut! Sorry to be a pest... we're about to start the Swift 3 port of our app, so I'm just wondering if this is close to being pushed? The offer of help is still on the table. :)

**Comment by AYastrebov** [comment]
Any progress?

**Comment by JimRoepcke** [comment]
I have a fork that's Swift 3 compatible and refactored to improve the metadata situation.

https://github.com/JimRoepcke/YapDatabaseExtensions
